FROM python:3.7-alpine
MAINTAINER James Alexander <j.alexanderbryant@gmail.com>

RUN apk update && apk add linux-headers libpq musl-dev libc-dev
RUN apk add gcc postgresql-dev python3-dev

WORKDIR '/app'

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

COPY ./ ./
RUN pip install --editable .

CMD gunicorn -b 0.0.0.0:8000 --access-logfile - "app.app:create_app()"
